### ISSUE TITLE
App Installer failed to install package dependencies. Ask the developer for  package. 

### ISSUE THREAD

**Issue by Geronimooo** [AJLeuer/GHelper#1]
I have a normal Windows 10 Pro:
19044.1415 
21H2

tried GHelper (Package)_1.1.1.0_x64.msixbundle and the previous version, both give the same error.

![image](https://user-images.githubusercontent.com/1741553/148582629-5ecaac24-a749-428e-a6e4-e8eb73542ac7.png)

**Comment by AJLeuer** [comment]
Really odd. Sorry about that. Honestly at first glance I'm not sure why that's happening. Let me do some research and I'll get back to you.

**Comment by AJLeuer** [comment]
Try installing with [this version](https://drive.google.com/file/d/1SKMbsFGnLAc1ckU-AMPPcLv3uVujX80D/view?usp=sharing). That includes the dependencies that the VS "Create App Packages" dialogue creates. I've never really known if I needed to include those or not but maybe not including them was the cause of your problem?

Anyway let me know if you have any better luck, or if the same thing still happens.

**Comment by Geronimooo** [comment]
The GHelper (Package)_1.1.1.0_x64.msixbundle gives the same error as before.

Install.ps1 I had to put my machines executionpolicy to Unrestricted and enable Developer Mode for Windows. Then it installed.
I suggest you create a virtual machine with a fresh install of Win 10 so you can test the dependency requirements.

I tried deleting the one in the pic, it vanished but not from g-hub and it was back when I restarted g-helper.
![image](https://user-images.githubusercontent.com/1741553/149169595-39bf3627-4047-4020-bc40-311e93a25cb8.png)
The CYBERPUNK2077x is posted as a "Custom Application" (the one I want to keep). You can edit the name (which I did) but on the "Standard Application" I cannot edit the name. But this probably merits its own bug-thread.

**Comment by AJLeuer** [comment]
Disabling editing names of standard applications is intended. GHelper edits G Hub's saved applications and profiles by changing the file `settings.db`. The problem is that G Hub at runtime disregards any changes made to its `settings.db` that change the name of a known application: it gets that name from some other file, as far as I can tell, and then copies the name back to `settings.db`, overwriting your changes. That's why I disabled changing application names unless they're custom.

And in fact, it turns out I need to remove the delete button for standard applications as well for a similar reason: G Hub does endless run-time checks that will just add back any applications you try to delete. I should have realized deleting applications wouldn't work with the way G Hub behaves. It's really frustrating.

But thanks for the suggestion. If I have time I'll try to look into why it won't install in certain scenarios. It doesn't appear that it's simply Windows 10 that's the problem, as other people on Windows 10 have been able to install it. It also shouldn't require developer mode as far as I know...

**Comment by Geronimooo** [comment]
Yes, I wondered if g-hub did something at startup and you confirmed it.

About the win 10 thing, I have two other computers with win 10, tried to install on both of them (one is a laptop) and I get the same error unfortunately. That points to that its not that uncommon, unless I have done something on all three of them that disallows installing it.

**Comment by AJLeuer** [comment]
All 3 have the same error, eh? Well you got me there. 

I'll be honest the behavior of Microsoft's installer for UWP/WinUI apps is something of a mystery to me. It seems to work most of the time but occasionally it'll just fail and spit out cryptic errors, like in your case. And I don't really have any insight into why it behaves the way it does.

I'll try to look into it though.

**Comment by AJLeuer** [comment]
Oh I had one other idea. In the zipped folder I linked before, there should be a bunch of `.appx` installers in the subfolder `Dependencies\x64\`. Try installing them all first, _then_ try installing `GHelperxxx.msixbundle` and see if that doesn't fix the installer error.

**Comment by Geronimooo** [comment]
Ah yes, I should have thought of checking that folder. Yes it worked to install it on one of the computers after installing the dependencies!

**Comment by AJLeuer** [comment]
Wow, honestly surprised that worked. Good to hear though. I only wish the installer would install those dependencies automatically, because I have a feeling you won't be the last person to have this issue.
